apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "financial-sim.fullname" . }}-operator
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "financial-sim.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      {{- include "financial-sim.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: operator
  template:
    metadata:
      labels:
        {{- include "financial-sim.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: operator
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "financial-sim.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.security.podSecurityContext | nindent 8 }}
      containers:
        - name: operator
          securityContext:
            {{- toYaml .Values.security.securityContext | nindent 12 }}
          image: "{{ .Values.operator.image }}:{{ .Values.global.imageTag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "{{ include "financial-sim.fullname" . }}-operator"
            - name: LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: LOG_FORMAT
              value: {{ .Values.logging.format | quote }}
            - name: METRICS_PORT
              value: "8080"
            {{- if .Values.zeromq.tcpKeepalive }}
            - name: ZEROMQ_TCP_KEEPALIVE
              value: "1"
            - name: ZEROMQ_TCP_KEEPALIVE_IDLE
              value: {{ .Values.zeromq.tcpKeepaliveIdle | quote }}
            - name: ZEROMQ_TCP_KEEPALIVE_INTERVAL
              value: {{ .Values.zeromq.tcpKeepaliveInterval | quote }}
            {{- end }}
            - name: ZEROMQ_HWM
              value: {{ .Values.zeromq.hwm | quote }}
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/financial-sim
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "financial-sim.fullname" . }}-config
      {{- with .Values.operator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}