apiVersion: v1
kind: Service
metadata:
  name: {{ include "financial-sim.fullname" . }}-operator
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "financial-sim.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
spec:
  type: {{ .Values.operator.service.type }}
  ports:
    - port: {{ .Values.operator.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "financial-sim.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: operator